// Client-side full-text search backed by Pagefind.
//
// The index is generated at build time by `scripts/build-search-index.mjs` and
// served from `/pagefind`. Pagefind loads a small WASM runtime plus only the
// index chunks a query touches, so the browser never downloads the ~30 MB of
// message bodies the archive holds.

import type { MessageView } from "@/app/messages-table/columns"

export interface SearchHit extends MessageView {
  excerpt: string
}

export type SearchSortKey = "id" | "title" | "date"

export interface SearchOptions {
  source?: "all" | "messageCenter" | "roadmap"
  services?: string[]
  // Omit to rank by relevance (recency-weighted). Naming a column sorts the
  // whole match set inside the index instead, so the ordering holds for
  // results that have not been fetched yet.
  sort?: { key: SearchSortKey; descending: boolean }
}

interface PagefindMeta {
  id?: string
  title?: string
  services?: string
  date?: string
  lastUpdated?: string
  source?: string
  sourceLabel?: string
  isMajor?: string
  isArchived?: string
}

interface PagefindData {
  url: string
  excerpt: string
  meta: PagefindMeta
}

export interface PagefindResult {
  id: string
  score: number
  data: () => Promise<PagefindData>
}

interface PagefindSearchOptions {
  filters?: Record<string, string[]>
  sort?: Record<string, "asc" | "desc">
}

interface PagefindModule {
  init: () => Promise<void>
  options: (options: Record<string, unknown>) => Promise<void>
  search: (
    query: string,
    options?: PagefindSearchOptions
  ) => Promise<{ results: PagefindResult[] }>
}

// How much a post's recency can lift its relevance score. The newest match in
// a result set is scored `1 + RECENCY_WEIGHT` times its relevance, the oldest
// gets no lift, and everything in between scales linearly by its position in
// the date order.
//
// Message Center relevance scores sit in tight clusters — adjacent hits are
// routinely within a percent of each other — so a 20% spread reliably sorts a
// tied cluster newest-first, which is what matters for change alerts. It is
// still small enough that a decisively better match (Pagefind scores those
// 2-3x higher) stays on top however old it is.
const RECENCY_WEIGHT = 0.2

let pagefindPromise: Promise<PagefindModule> | null = null

async function getPagefind(): Promise<PagefindModule> {
  if (!pagefindPromise) {
    pagefindPromise = (async () => {
      // The specifier is held in a variable and marked webpackIgnore so the
      // bundler leaves it alone: the file is generated by the index build and
      // is fetched from the site root at runtime.
      const modulePath = "/pagefind/pagefind.js"
      const pagefind = (await import(
        /* webpackIgnore: true */ modulePath
      )) as unknown as PagefindModule
      await pagefind.options({ excerptLength: 30 })
      await pagefind.init()

      return pagefind
    })().catch((error) => {
      // Let the next attempt retry instead of caching the failure forever.
      pagefindPromise = null
      throw error
    })
  }

  return pagefindPromise
}

export async function searchMessages(
  query: string,
  options: SearchOptions = {}
): Promise<PagefindResult[]> {
  const pagefind = await getPagefind()
  const filters: Record<string, string[]> = {}

  if (options.source && options.source !== "all") {
    filters.source = [options.source]
  }

  if (options.services?.length) {
    filters.service = options.services
  }

  const searchOptions: PagefindSearchOptions = Object.keys(filters).length
    ? { filters }
    : {}

  if (options.sort) {
    const response = await pagefind.search(query, {
      ...searchOptions,
      sort: { [options.sort.key]: options.sort.descending ? "desc" : "asc" },
    })

    return response.results ?? []
  }

  // Two passes over the same match set: one by relevance, one by date. The
  // date pass is only used for its ordering, which avoids pulling a fragment
  // per result just to read a date off it.
  const [byRelevance, byDate] = await Promise.all([
    pagefind.search(query, searchOptions),
    pagefind
      .search(query, { ...searchOptions, sort: { date: "desc" } })
      .catch(() => null),
  ])

  const results = byRelevance.results ?? []

  return applyRecencyWeighting(results, byDate?.results ?? [])
}

// Re-rank relevance-ordered results so newer posts win among comparable
// matches. `byDate` is the same set ordered newest-first; a post's position in
// it stands in for its age, which keeps the weighting relative to the result
// set rather than to a fixed date (a query about an old change still ranks its
// most recent posts first).
function applyRecencyWeighting(
  byRelevance: PagefindResult[],
  byDate: PagefindResult[]
): PagefindResult[] {
  if (byRelevance.length < 2 || byDate.length < 2) return byRelevance

  const oldestPosition = byDate.length - 1
  const datePositions = new Map(
    byDate.map((result, index) => [result.id, index])
  )

  return byRelevance
    .map((result, index) => {
      // Anything the date pass did not return is treated as oldest, so a
      // missing date can only cost a post its lift, never invent one.
      const position = datePositions.get(result.id) ?? oldestPosition
      const recency = 1 - position / oldestPosition

      return {
        result,
        // Relevance order breaks ties, so equally recent hits keep Pagefind's
        // ordering rather than shuffling between searches.
        index,
        score: result.score * (1 + RECENCY_WEIGHT * recency),
      }
    })
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .map((entry) => entry.result)
}

const escapeHtml = (value: string) =>
  value.replace(
    /[&<>"']/g,
    (char) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;",
      }[char] as string)
  )

// Pagefind wraps matches in <mark>. Everything else is escaped so a message
// body can never inject markup into the results list.
export function sanitizeExcerpt(excerpt: string | undefined): string {
  return escapeHtml(excerpt || "")
    .replace(/&lt;mark&gt;/g, "<mark>")
    .replace(/&lt;\/mark&gt;/g, "</mark>")
}

function toHit(data: PagefindData): SearchHit {
  const meta = data.meta || {}
  const source = meta.source === "roadmap" ? "roadmap" : "messageCenter"

  return {
    id: meta.id || data.url.split("/").pop() || "",
    title: meta.title || "Untitled",
    service: meta.services ? meta.services.split("|").filter(Boolean) : [],
    lastUpdated: meta.lastUpdated || undefined,
    date: meta.date || undefined,
    isMajor: meta.isMajor === "true",
    isArchived: meta.isArchived === "true",
    source,
    sourceLabel:
      meta.sourceLabel ||
      (source === "roadmap" ? "Microsoft 365 Roadmap" : "Message Center"),
    excerpt: sanitizeExcerpt(data.excerpt),
  }
}

export async function loadSearchHits(
  results: PagefindResult[],
  start: number,
  count: number
): Promise<SearchHit[]> {
  const slice = results.slice(start, start + count)
  const data = await Promise.all(slice.map((result) => result.data()))

  return data.map(toHit)
}
