// Client-side full-text search backed by Pagefind.
//
// The index is generated at build time by `scripts/build-search-index.mjs` and
// served from `/pagefind`. Pagefind loads a small WASM runtime plus only the
// index chunks a query touches, so the browser never downloads the ~30 MB of
// message bodies the archive holds.

import type { MessageView } from "@/app/messages-table/columns"

export interface SearchHit extends MessageView {
  excerpt: string
}

export interface SearchOptions {
  source?: "all" | "messageCenter" | "roadmap"
  services?: string[]
}

interface PagefindMeta {
  id?: string
  title?: string
  services?: string
  date?: string
  lastUpdated?: string
  source?: string
  sourceLabel?: string
  isMajor?: string
  isArchived?: string
}

interface PagefindData {
  url: string
  excerpt: string
  meta: PagefindMeta
}

export interface PagefindResult {
  id: string
  data: () => Promise<PagefindData>
}

interface PagefindModule {
  init: () => Promise<void>
  options: (options: Record<string, unknown>) => Promise<void>
  search: (
    query: string,
    options?: { filters?: Record<string, string[]> }
  ) => Promise<{ results: PagefindResult[] }>
}

let pagefindPromise: Promise<PagefindModule> | null = null

async function getPagefind(): Promise<PagefindModule> {
  if (!pagefindPromise) {
    pagefindPromise = (async () => {
      // The specifier is held in a variable and marked webpackIgnore so the
      // bundler leaves it alone: the file is generated by the index build and
      // is fetched from the site root at runtime.
      const modulePath = "/pagefind/pagefind.js"
      const pagefind = (await import(
        /* webpackIgnore: true */ modulePath
      )) as unknown as PagefindModule
      await pagefind.options({ excerptLength: 30 })
      await pagefind.init()

      return pagefind
    })().catch((error) => {
      // Let the next attempt retry instead of caching the failure forever.
      pagefindPromise = null
      throw error
    })
  }

  return pagefindPromise
}

export async function searchMessages(
  query: string,
  options: SearchOptions = {}
): Promise<PagefindResult[]> {
  const pagefind = await getPagefind()
  const filters: Record<string, string[]> = {}

  if (options.source && options.source !== "all") {
    filters.source = [options.source]
  }

  if (options.services?.length) {
    filters.service = options.services
  }

  const response = await pagefind.search(
    query,
    Object.keys(filters).length ? { filters } : undefined
  )

  return response.results ?? []
}

const escapeHtml = (value: string) =>
  value.replace(
    /[&<>"']/g,
    (char) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&#39;",
      }[char] as string)
  )

// Pagefind wraps matches in <mark>. Everything else is escaped so a message
// body can never inject markup into the results list.
export function sanitizeExcerpt(excerpt: string | undefined): string {
  return escapeHtml(excerpt || "")
    .replace(/&lt;mark&gt;/g, "<mark>")
    .replace(/&lt;\/mark&gt;/g, "</mark>")
}

function toHit(data: PagefindData): SearchHit {
  const meta = data.meta || {}
  const source = meta.source === "roadmap" ? "roadmap" : "messageCenter"

  return {
    id: meta.id || data.url.split("/").pop() || "",
    title: meta.title || "Untitled",
    service: meta.services ? meta.services.split("|").filter(Boolean) : [],
    lastUpdated: meta.lastUpdated || undefined,
    isMajor: meta.isMajor === "true",
    isArchived: meta.isArchived === "true",
    source,
    sourceLabel:
      meta.sourceLabel ||
      (source === "roadmap" ? "Microsoft 365 Roadmap" : "Message Center"),
    excerpt: sanitizeExcerpt(data.excerpt),
  }
}

export async function loadSearchHits(
  results: PagefindResult[],
  start: number,
  count: number
): Promise<SearchHit[]> {
  const slice = results.slice(start, start + count)
  const data = await Promise.all(slice.map((result) => result.data()))

  return data.map(toHit)
}
